using System;
using MixedReality.Toolkit.UX;
using UnityEngine;
using UnityEngine.XR.ARFoundation;

/// <summary>
/// Script to create hand menu functionalities.
/// Authors: Joseph Chun, Kira Yoon
/// Date: March 27, 2024
/// Sources:
/// https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/manual/mesh-manager.html
/// https://learn.microsoft.com/en-us/dotnet/api/mixedreality.toolkit.ux.dialogpool?view=mrtkuxcore-3.0
/// https://docs.unity3d.com/ScriptReference/Rigidbody.html
/// https://learn.microsoft.com/en-us/windows/mixed-reality/design/hand-menu
/// </summary>
public class HandMenuScript : MonoBehaviour
{
    /// <summary>
    /// Set up instance variables.
    /// </summary>
    public DialogPool dialogPool;

    public ARMeshManager meshManager;
    
    private static Vector3 _spawnOffSet;
    [SerializeField] private string carName = "RaceCar_Blue";
    private GameObject _carGameObject;
    private Rigidbody _carRigidBody;
    
    /// <summary>
    /// Awake method to initialize the Hand menu script.
    /// </summary>
    void Awake()
    {
        if (dialogPool == null)
        {
            dialogPool = GetComponent<DialogPool>();
        }
        
        _carGameObject = GameObject.Find(carName);
        _carRigidBody = _carGameObject.GetComponent<Rigidbody>();
        _carGameObject.SetActive(false);
        ShowMeshManager(false);
    }
    
    /// <summary>
    /// Resets the car's position and rotation. Spawns the car in front of the user.
    /// </summary>
    public void ResetCar()
    {
        if (_carRigidBody == null || Camera.main == null) return;

        _carGameObject.SetActive(true);
        _spawnOffSet = new Vector3(0, .14f, 1.5f);

        var rbTransform = _carRigidBody.transform;
        var cameraTransform = Camera.main.transform;
        var cameraPosition = cameraTransform.position;
        var cameraRotation = cameraTransform.rotation;

        rbTransform.position = cameraPosition + cameraTransform.forward * _spawnOffSet.z + new Vector3(0, _spawnOffSet.y, 0);
        rbTransform.rotation = Quaternion.Euler(0, cameraRotation.eulerAngles.y, 0);
        _carRigidBody.velocity = Vector3.zero;
        _carRigidBody.angularVelocity = Vector3.zero;
    }

    /// <summary>
    /// Creates a dialog window for the user to exit the application.
    /// </summary>
    public void CreateExitDialog()
    {
        IDialog dialog = dialogPool.Get()
            .SetHeader("Exit Game")
            .SetBody("Are you sure you want to exit?")
            .SetPositive("Yes", (args) =>
            {
                Application.Quit();
            })
            .SetNegative("No");

        dialog.Show();
    }

    /// <summary>
    /// Hides the rendering for all meshes generated by the ARMeshManager.
    /// </summary>
    /// <param name="state"></param>
    private void ShowMeshManager(bool state)
    {
        try
        {
            meshManager.meshPrefab.GetComponent<Renderer>().enabled = state;
            
            var meshes = meshManager.meshes;
            foreach (var meshFilter in meshes)
            {
                meshFilter.GetComponent<Renderer>().enabled = state;
            }
            
        }
        catch (Exception e)
        {
            Debug.Log(e);
        }
    }

    /// <summary>
    /// Removes all meshes generated by the ARMeshManager.
    /// Source: https://forum.unity.com/threads/how-to-reset-meshes-generated-by-armeshmanager.1451887/
    /// Only way to reset the mesh manager is to disable and enable it
    /// </summary>
    public void ResetMeshManager()
    {
        try
        {
            meshManager.enabled = false;
            meshManager.DestroyAllMeshes();
            ShowMeshManager(true);
            meshManager.enabled = true;
        }
        catch (Exception e)
        {
            Debug.Log(e);
        }
    }
    
    /// <summary>
    /// Creates a dialog window for the user to remap the room.
    /// </summary>
    public void CreateRemapRoomDialog()
    {
        IDialog dialog = dialogPool.Get()
            .SetHeader("Reset Mapping")
            .SetBody(
                "Walk around to map your environment. " +
                "After you are done mapping, click Finish Mapping."
                )
            .SetNeutral("Finish Mapping", (args) =>
            {
                meshManager.enabled = false;
                ShowMeshManager(false);
                meshManager.enabled = true;
            });
        dialog.Show();
    }
}
